### ISSUE TITLE
What to do with unreferenced models that are just used through visibility

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1125]
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKIG1vZGVsIFRoxBl7CiAgQHZpc2liaWxpdHkoInVwZGF0ZSIpIHU%2FOiBzdHJpbmc70CRjcmXGJGPNJGlubmVyPzrGWjsKfQoKQHJvdXRlKCIvIikgQHBvc3Qgb3Agxj4oLi4uxSkpyDE%3D)

```cadl

import "@cadl-lang/rest";

using Cadl.Http;

model Thing {
  @visibility("update") u?: string;
  @visibility("create") c?: string;
  inner?: Thing;
}

@route("/") @post op create(...Thing): Thing;

```

As part of this PR #1123, the output will now be 3 schemas `ThingCreate` `ThingRead` and new `Thing`. As Thing itself wasn't being represented before.

**Comment by nguerrera** [comment]
Upside of emitting `Thing` in this case is that you can debug a little easier by comparing ThingRead to Thing in swagger. I think this is probably a fine change.

But we could get back the old behavior relatively easily, if we want it, I think. We could do the emit all models last and skip a model that already has at least one schema. I'm just not sure we want it.

**Comment by markcowl** [comment]
@timotheeguerin @nguerrera Can't we get the old behavior by emitting models based on usage in operations?

**Comment by timotheeguerin** [comment]
## Old Behavior
include every view of a model for the used visibility(e.g. `UserRead`, `UserCreate`)

## New Behavior
- (Same) include every view of a model for the used visibility(e.g. `UserRead`, `UserCreate`)
- (+) include the base model (User)
- if using `omit-unreachable-types: true` its back to the old behavior

## Solutions

1. What we have now is good?
2. Only include the base model if none of the view are already included

**Comment by nguerrera** [comment]
I now think we should do (2). Emitting the "base" model suppresses code that used to avoid suffixes if there was only ever one that was used.

**Comment by timotheeguerin** [comment]
1. try to represent as a single model (with readonly if possible)
2. if not generate each different model but don't include base model
3. unreachable models stays as they are: included unless `omit-unreachable-types: true`
```cadl
model User {
  name: string;
  @visibility("create") password: string;
  @visibility("read") id: string;
}
op create(user: User): void;
op read(): User;
```

```yaml
components:
  schemas:
    UserRead:
      properties:
        id: { type: string }
        name: { type: string }
    UserCreate:
      properties:
        name: { type: string }
        password: { type: string }
    
    # Never include non used visibility
    # UserUpdate:
    #   properties:
    #    ...
       
    # this schema is not referenced in operations 
    User:
      properties:
        id: { type: string }
        name: { type: string }
        password: { type: string }
```
