### ISSUE TITLE
[Feature Request] replace variable with input values in cadl-project.yaml in cadl command

### ISSUE THREAD

**Issue by dw511214992** [microsoft/cadl#1159]
In autorest, we can input value to replace variable in readme.md. For example, there is a `readme.typescript.md`:
```
title: AgriFoodMgmtClient
typescript:
  package-name: "@azure/arm-agrifood"
  output-folder: "$(typescript-sdks-folder)/sdk/agrifood/arm-agrifood"
```
We can use `autorest --typescript-sdks-folder=/path/to/js/repo` to replace the `output-folder` in running time. 
__This feature is very important in integrating CADL+DPG in sdk automation pipeline.__
So, we hope CADL command can support inputing variable to replace the dynamic variable in `cadl-project.yaml`. For example, If there is a `cadl-project.yaml`:
```
emitters:
  "@azure-tools/cadl-python": 
        "output-folder": $(python-sdks-folder)/sdk/agrifood/azure-mgmt-agrifood/azure/mgmt/agrifood
```
I hope to specify the value of `python-sdks-folder` with command `cadl compile --python-sdks-folder=/path/to/python/repo`.

**Comment by weshaggard** [comment]
@allenjzhang is this something you think we can do? It will become critical for some of the automation work.

**Comment by dw511214992** [comment]
To unblock our work, we propose two workaround solutions here: 
1. Use cald's parameter `output-path` and `sdk-folder` defined in `cadl-project.yaml` to generate codes. (Details can be found in https://github.com/Azure/cadl-azure/issues/2104#issuecomment-1277147248)
   1. Shanghai team also have a discussion about the workaround solution and have a concern here: We use cadl’s parameter “input-path” as a part of final path to generate codes, which violates the parameter’s original purpose (we should use the “input-path” as the final path to generate codes). 
3. Use the value option `sdk-folder` defined in `cadl-project.yaml`  to generate codes.
   1. This task asks sdk automation script to add a prefix to the value of “sdk-folder”, and the prefix is the path of the sdk repo. Then the value of “sdk-folder” is the absolute path of output folder.
@weshaggard  @allenjzhang  What do you think about these two solutions?  (We are using the second solution for implementation temporarily)

**Comment by allenjzhang** [comment]
As I mentioned in the email, I am not sure about introducing "SDK" specific configurations as opposed to some generic way to allow custom configurations. We will triage this today.

**Comment by dw511214992** [comment]
@allenjzhang  Is there any update?

**Comment by timotheeguerin** [comment]
It was triaged for a design discussion, we are not just going to allow this to work.Emitters options are strictly defined right now and allowing free form options is going to cause a lot of typo issues. As the other issue #1776 also point out we have an important discussion on how `output-dir` is going to work.

Right now you are in control of your `output-file` option so you can do your own interpolation if you want.

**Comment by timotheeguerin** [comment]
# Proposal

## Problem

A Cadl project would like to define their own variables that the emitter shouldn't be aware of. (e..g. `python-sdks-folder` being a flag that only make sense in the context of the azure python repo)

## Solutions

### 1. Allow environment variable interpolation

A cadl project file can then use `{}` to interpolate environment variables

```yaml
emitters:
  "@azure-tools/cadl-python":
    "output-dir": {PYTHON_SDK_FOLDER}/sdk/agrifood/azure-mgmt-agrifood/azure/mgmt/agrifood

    # Alternative explicit source
    "output-dir": {env.PYTHON_SDK_FOLDER}/sdk/agrifood/azure-mgmt-agrifood/azure/mgmt/agrifood
```

and it can be used like this

```bash
PYTHON_SDK_FOLDER=/path/to/sdk cadl compile .
```

Pros:

- simple and flexible

Cons:

- not strongly typed
- not the nicest experience to use(specially on windows)
- no defaults
- could get polluted by something else setting the env variable

## 2. List a set of parameters for a cadl-project.yaml

Similar to dockerfile args https://docs.docker.com/engine/reference/builder/#arg

```yaml
parameters:
  python-sdk-folder:
    default: ./foo

emitters:
  "@azure-tools/cadl-python":
    "output-dir": {python-sdk-folder}/sdk/agrifood/azure-mgmt-agrifood/azure/mgmt/agrifood

    # Alternative explicit source
    "output-dir": {params.python-sdk-folder}/sdk/agrifood/azure-mgmt-agrifood/azure/mgmt/agrifood
```

Usage

```bash
cadl compile . --arg python-sdk-folder=custom
```

Pros:

- explicit params, we can validate for unknown args
- cli looks clean
- we can have default so the `--arg` is always optional

Cons:

- more verbose
