### ISSUE TITLE
Add support for language sub directories when generating multiple languages

### ISSUE THREAD

**Issue by m-nash** [microsoft/cadl#1176]
Carry over from the conversation started [here](https://github.com/microsoft/cadl/issues/1103#issuecomment-1282825588)

It also doesn't let people override the name of each language sub folder.

For instance if I want to put all generated libraries under a folder called `Libraries` I would use the command `cadl compile . --output-dir ./Libraries`.

If each emitter did as you suggested and did its own concatenation this would result in
- main.cadl
- cadl-project.yaml
- package.json
- Libraries
  - cadl-csharp
  - cadl-java
  - cadl-python

Now lets say I wanted to change the name of the sub folder for cadl-csharp to be dotnet I would need to know ahead of time the command line parameter that is going to be passed into cadl compile command

For example if I have this cadl-project.yaml
```yaml
  "@azure-tools/cadl-csharp":
    "output-dir": "./Libraries/dotnet"
```
and I use this command `cadl compile . --output-dir ./Libraries`
I will get the desired result of
- main.cadl
- cadl-project.yaml
- package.json
- Libraries
  - dotnet
  - cadl-java
  - cadl-python

However if I use this command `cadl compile . --output-dir ./GeneratedLibraries` with the same cadl-project.yaml
I will get the undesired result of
- main.cadl
- cadl-project.yaml
- package.json
- Libraries
  - dotnet
- GeneratedLibraries
  - cadl-java
  - cadl-python

Having the compiler understand a global output dir and a per emitter output dir separately and do the concatenation itself allows us to use the following project cadl-project.yaml file
```yaml
  "@azure-tools/cadl-csharp":
    "output-dir": "dotnet"
```
which will have the desired result for both commands since the emitter simply uses whatever output-dir was given to it and only needs to worry about the sub structures inside the language folder

**Comment by m-nash** [comment]
Yes, if its not a combination OR we provide a magic interpolation then you cannot achieve the desired result or defining where ALL emitters should output if one of them overrides the output-dir.

Not suggesting my way to solve the problem is the only way, but it is a problem at the moment that needs to be solved.

It could also be that this is 2 concepts that we are trying to represent with 1 variable.
`ProjectRoot` and `EmitterRoot`?  Where `EmitterRoot` is always relative to `ProjectRoot`?

**Comment by tjprescott** [comment]
A few things:
1. I tried to do this and there is a bug that the hardcoded folder (in this case `dotnet`) will not be created and the `cadl compile` will fail. You have to manually go and create that folder for it to succeed. This should not be the case.
2. There were a few different ways I tried to piece together this path, which illustrates the possbility (if not likelihood) that each emitter is going to do its own thing. It would be better if the `cadl compile` step orchestrated this. Hence, passing a path into each emitter of the format `{program.compilerOptions.outputDir}/{emitterName}/` would drive consistency across emitters and avoid this duplication (at best) of logic in each emitter or proliferation of variants (at worst).

**Comment by allenjzhang** [comment]
I echo Timothee's comment My preference is to have a clear definition of --out-dir rather than overload its meaning such as just "dotnet" and expect it to be a concatenation. With a few well-defined tokens, it can be overwritten to the heart's content.  And by default, we can simply choose to append the emitter name to `--out-dir` from the command line. So in effect, `out-dir` has default value of `{ProjectRoot}/Cadl-output/{EmitterName}` unless it is overridden.

**Comment by m-nash** [comment]
`--out-dir` is already overloaded which is exactly what I am trying to unwind.

I guess the problem is what if I only want to override the `EmitterName` portion of `{ProjectRoot}/Cadl-output/{EmitterName}`?  Today there is no way to know `ProjectRoot` at the time that I write the cadl-project.yaml file since it won't be known until its passed in on the command line.

It gets really awkward to have `output-dir` on the command line and `output-dir` (with a different meaning) in the cadl-project.yaml file.  Typically commandline trumps configuration files and in this case if I override it in the configuration file it will trump the commandline?

I am ok if we separate the two concepts into two parameters `ProjectRoot` and `EmitterRoot` (names to be determined) and provide a mechanism for people to reference the `ProjectRoot` from the cadl-project.yaml.  This would accomplish the same thing since then I could use this in my configuration file as Timothee mentioned above

```yaml
"@azure-tools/cadl-csharp":
    "emitter-root": "{ProjectRoot}/dotnet"
```
Or I can use an absolute path to move the dotnet output to be something completely unrelated to the `ProjectRoot` like this
```yaml
"@azure-tools/cadl-csharp":
    "emitter-root": "C:/MyArtifacts/dotnet"
```

In either case we achieve the goal of each emitter having a clear path given to them and all they need to do is create the sub structure inside that root directory and not worry about having to create an isolation layer just in case multiple languages are being created at the same time.

**Comment by timotheeguerin** [comment]
Maybe there is some confusion here but just to clarify what the current behavior is

`--output-dir`: Default output directory to be used

```yaml
output-dir: ./my-output # <-- not available right now but we have an issue. This si the same as passing `--output-dir`

emitters:
  "@azure-tools/cadl-csharp":
     "output-dir": ./my-output/subfolder-for-csharp // Set the output-dir for the csharp emitter
  "@azure-tools/cadl-python":
     "output-dir": ./my-output/subfolder-for-python // Set the output-dir for the csharp emitter
```

`{ProjectRoot}` as talked about before is not unknown it would be the path of the `cadl-project.yaml`. It is a way to take out the relative path out of the picture. Like `${workspaceFolder}` in vscode settings.


## Problem with what we have

If I understand the problem with that flow is given this cadl-project.yaml
```yaml
output-dir: ./my-output

emitters:
  "@azure-tools/cadl-csharp":
     "output-dir": ./my-output/subfolder-for-csharp // Set the output-dir for the csharp emitter
  "@azure-tools/cadl-python":
     "output-dir": ./my-output/subfolder-for-python // Set the output-dir for the csharp emitter
```

if I wanted to change the common output-dir I would have to update every single path so my cli would be 
```
cadl compile .
  --output-dir=./different-out
  --option "@azure-tools/cadl-csharp.output-dir=./different-out/subfolder-for-csharp"
  --option "@azure-tools/cadl-python.output-dir=./different-out/subfolder-for-python"
```

which is definitely not optimal. What I suggest and we talked about before is to have a way to reference the common output dir in emitter options so you could have the follow project file:
```yaml
output-dir: ./my-output

emitters:
  "@azure-tools/cadl-csharp":
     "output-dir": {compiler-output-dir}/subfolder-for-csharp // Set the output-dir for the csharp emitter
  "@azure-tools/cadl-python":
     "output-dir": {compiler-output-dir}/subfolder-for-python // Set the output-dir for the csharp emitter
```
then using `--output-dir` will update every single one

**Comment by dw511214992** [comment]
Hi @timotheeguerin as requested in https://github.com/microsoft/cadl/issues/1159, can we support using variable in output-dir? For example, when I have a `cadl-project.yaml`:
```
output-dir: ./my-output

emitters:
  "@azure-tools/cadl-csharp":
     "output-dir": ${net-sdk-repo}/subfolder-for-csharp # Set the output-dir for the csharp emitter
  "@azure-tools/cadl-python":
     "output-dir": ${python-sdk-repo}/subfolder-for-python # Set the output-dir for the csharp emitter
```
I can generate csharp and python sdk in their sdk repository separately by using command: `cadl compile . --net-sdk-repo /path/to/net/sdk/repo --python-sdk-repo /path/to/python/sdk/repo`. Based on my understanding, we want to generate each language of sdk in different sdk repository in most times, and it means we don't need  the same `output-dir ` in this scenario.

**Comment by tjprescott** [comment]
> I can generate csharp and python sdk in their sdk repository separately by using command: cadl compile . --net-sdk-repo /path/to/net/sdk/repo --python-sdk-repo /path/to/python/sdk/repo. Based on my understanding, we want to generate each language of sdk in different sdk repository in most times, and it means we don't need the same output-dir in this scenario.

How much do we expect to need to manual generate SDKs vs. CI doing it automatically? If the CI can generate the build artifacts and move them to the right places, then having totally disparate paths is not as important. However, right now, everything gets dumped and mixed together in a single `cadl-output` folder and this makes separating the artifacts tedious at best.

While we could have every emitter do this with some kind of boilerplate, I think having `cadl compile` handle this makes the most sense since it guarantees all emitters can rely on the same behavior.

**Comment by timotheeguerin** [comment]
other problem that we are going to have with multiple `@service` is each service should get generated to a different output path. So you might have this structure

```
./common-folder/emitter/service-name/output.json
```

**Comment by timotheeguerin** [comment]
# Output dir resolution

Goals:

- find a good default for each emitter `output-dir`
- provide good configurability by user

Items to take into consideration:

- **common dir**: have a way for each emitter to be relative to a common dir
- **emitter output dir unique**: Have 2 emitter should by default not conflict each other
- **multi service structure**: Emitter should have an good way to structure the output per service(but it should be configureable)
- **multi version structure**: Emitter should have an good way to structure the output per version(but it should be configureable)

## Proposal

### Step 1: Make `output-dir` a special emitter options

This mean that this option is already available for each emitter and they don't have to define it.

Emitter interface can be updated to

```ts
// in @cadl-lang/compiler
interface EmitContext<T extends EmitterOptions> {
  program: Program;
  outputDir: string; // Output dir resolved for your emitter.
  options: T;
}

// in emitter.ts
interface MyEmitterOptions {}
export function $onEmit(context: EmitContext<MyEmitterOptions>) {}
```

This is breaking but it would be inline with decorators, should maybe do similar things for functions and onValidate

### Step 2: [Optional] Rename compiler `output-dir` to `base-output-dir`

Idea behind the rename is that we want to see the compiler output-dir as the common base for all emitter output-dir unless configured otherwise for an emitter. Keeping it `output-dir` does makes it confusing that emitter `output-dir` might depend on it.

This means also updating the cli `--base-output-dir`

Alternative names:

- `common-output-dir`
- `root-output-dir`

## Step 3: Default resolution for emitter `output-dir`

The emitter output-dir by default could resolve to `{base-output-dir}/{emitter-name}` where

- `{base-output-dir}` is the compiler
- `{emitter-name}` is emitter name that should be the package name.

```yaml
emitters:
  @azure-tools/cadl-python: true
  @azure-tools/cadl-csharp: true
```

This means the default output would produce this folder structure

```
cadl-output/
  @azure-tools/
    cadl-csharp/
    cadl-python/
```

Tweak here that we could do:

- if there is only a single emitter we could not do the nesting?
  - issue with this is adding/removing emitter might completely change the output structure.
- emitter name could be skip the package name scope(in this case `cadl-sharp` and `cadl-python`) but this increase conflict chances. Should we then also have teh same logic for everything else(diagnostics, way to reference the emitter, etc.)
- emitter name could instead be another built-in options for each emitter called `emitter-folder` that default to one of the above but would let user just override that.

## Step 4: User configuration

For a user to be able to change the output dir we would make `{base-output-dir}` and `{emitter-name}` as available interpolation variables

### Scenario 1: user just wants to change the commin folder to be somewhere else

```yaml
output-dir: ./other-output
emitters:
  @azure-tools/cadl-python: true
  @azure-tools/cadl-csharp: true
```

or via the cli

```bash
cadl compile --base-output-dir ./other-output
```

The resulting folder structure would be

```
other-output/  <--- changed this only
  @azure-tools/
    cadl-csharp/
    cadl-python/
```

### Scenario 2: user wants to change an emitter output

```yaml
emitters:
  @azure-tools/cadl-python:
    output-dir: "{base-output-dir}/sdks/python"
  @azure-tools/cadl-csharp: true
```

or via the cli

```bash
cadl compile --option "@azure-tools/cadl-python.output-dir={base-output-dir}/sdks/python"
```

The resulting folder structure would be

```
cadl-output/
  @azure-tools/
    cadl-csharp/
  sdks/ <--- changed output for python emitter
    python/
```

### Step 5: Service name and versioning

If you have multiple `@service` and/or some service has multiple versions each service version needs to be scoped into its own structure.

This might be a per emitter decision but it would be good to maybe have an helper to resolve scoped path.

Thinking for example

- openapi3: `{base-output-dir}/{emitter-name}/{serviceName?}/{file-name}.{version?}.json`
  - Result in:
    - `./cadl-output/@cadl-lang/openapi3/Service1/openapi.2022-01-01.json`
    - single service with 1 version `./cadl-output/@cadl-lang/openapi3/openapi.json`. Don't include the service name and version if there is only one
- cadl-autorest: `{base-output-dir}/{emitter-name}/{serviceName?}/{version?}/{file-name}.json`
  - `./cadl-output/@azure-tools/cadl-autorest/Service1/2022-01-01/openapi.json`
  - single service with 1 version `./cadl-output/@azure-tools/cadl-autorest/openapi.json`

To do that we could have an helper

```ts
export function resolveScopedPath(
  template: string,
  args: Record<string, string>
);
```

usage would be as follow

```ts

const template `./cadl-output/@cadl-lang/openapi3/{serviceName?}/{file-name}.{version?}.json`
//                ^ that part already been resolved by the emitter options
resolveScopedPath(template, args: {
  "service-name": "MyService",
  "file-name": context.options["file-name"] ?? "openapi.json",
}); // ./cadl-output/@cadl-lang/openapi3/Service1/openapi.json
resolveScopedPath(template, args: {
  "service-name": "MyService",
  version: "2022-01-01",
  "file-name": context.options["file-name"] ?? "openapi.json",
}); // ./cadl-output/@cadl-lang/openapi3/Service1/openapi.2022-01-01.json

ScopedPath(template, args: {
  "file-name": context.options["file-name"] ?? "openapi.json",
}); // ./cadl-output/@cadl-lang/openapi3/openapi.json
```

**Comment by dw511214992** [comment]
@timotheeguerin thanks for your proposal.
Based on my understanding, If I have the following `cadl-project.yaml`:
```
emitters:
  "@azure-tools/cadl-csharp":
     "output-dir": {base-output-dir}/subfolder-for-csharp # Set the output-dir for the csharp emitter
  "@azure-tools/cadl-python":
     "output-dir": {base-output-dir}/subfolder-for-python # Set the output-dir for the csharp emitter
```
and I want to generate csharp and python codes in two repositories separately, I can use the following two commands to generates codes twice:
```
cadl compile . --emit @azure-tools/cadl-csharp --base-output-dir /absolute/path/to/net/sdk/repository
```
```
cadl compile . --emit @azure-tools/cadl-python --base-output-dir /absolute/path/to/python/sdk/repository
```
Then I can get generated csharp codes in `/absolute/path/to/net/sdk/repository/subfolder-for-csharp`, and get generated python codes in `/absolute/path/to/net/sdk/repository/subfolder-for-python`. Is it right?

**Comment by m-nash** [comment]
@timotheeguerin thank you for summarizing everything looks good I have one clarifying question

- Should a user be able to use an absolute path in their cadl-project.yaml?

**Comment by markcowl** [comment]
@m-nash  I think there are two separate questions
- what should a microsoft user of azure emitters do
- what will the tooling prevent a user from doing

Since the cli is a general tool for all kinds of users, we would generally avoid enforcing this kind of restriction in the cli itself, but I would think we sould encourage users to use relative paths.

**Comment by markcowl** [comment]
# `output-dir` Revised Proposal

Goals:

- find a good default for each emitter `output-dir`
- provide good configurability by user

Items to take into consideration:

- **common dir**: have a way for each emitter to be relative to a common dir
- **emitter output dir unique**: Have 2 emitter should by default not conflict each other

## Rename emitter `output-dir` to `emitter-output-dir`

Idea behind the rename is that we want to see the compiler output-dir as the common base for all emitter emitter-output-dir unless configured otherwise for an emitter. Keeping the emitter value as `output-dir` creates confusion about how the values differ.

## Make `emitter-output-dir` a special emitter option

This mean that this option is already available for each emitter and they don't have to define it.

Emitter interface can be updated to

```ts
// in @cadl-lang/compiler
interface EmitContext<T extends EmitterOptions> {
  program: Program;
  emitterOutputDir: string; // Output dir resolved for your emitter.
  options: T;
}

// in emitter.ts
interface MyEmitterOptions {}
export function $onEmit(context: EmitContext<MyEmitterOptions>) {}
```

This is breaking but it would be inline with decorators, should maybe do similar things for functions and onValidate

## Default resolution for emitter `emitter-output-dir`

The emitter emitter-output-dir by default woukld resolve to `{output-dir}/{emitter-name}` where

- `{output-dir}` is the compiler output directory setting
- `{emitter-name}` is emitter name that should be the package name.

```yaml
emitters:
  @azure-tools/cadl-python: true
  @azure-tools/cadl-csharp: true
```

This means the default output would produce this folder structure

```
cadl-output/
  @azure-tools/
    cadl-csharp/
    cadl-python/
```

## User configuration

### Basic Interpolation
We will enable static interpolation variables:

| Name | Value |
| --- | --- |
| `{output-dir}` | The value of the global `output-dir` setting |
| `{emitter-name}` | corresponds to the name of the emitter |
| `{cwd}` | corresponds to the current working directory |
| `{project-root}` | corresponds to the directory |

For a user to be able to change the output dir we will allow `{output-dir}` and `{emitter-name}` as available interpolation variables

#### Scenario 1: user just wants to change the common output folder to be somewhere else

```yaml
"output-dir": "{cwd}/other-output"
emitters:
  "@azure-tools/cadl-python": true
  "@azure-tools/cadl-csharp": true
```

or via the cli

```bash
cadl compile --output-dir ./other-output
```

The resulting folder structure would be

```
other-output/  <--- changed this only
  @azure-tools/
    cadl-csharp/
    cadl-python/
```

#### Scenario 2: user wants to change an emitter output

```yaml
emitters:
  "@azure-tools/cadl-python":
    "emitter-output-dir": "{output-dir}/sdks/python"
  "@azure-tools/cadl-csharp": true
```

or via the cli

```bash
cadl compile --option "@azure-tools/cadl-python.emitter-output-dir={output-dir}/sdks/python"
```

The resulting folder structure would be

```
cadl-output/
  @azure-tools/
    cadl-csharp/
  sdks/ <--- changed output for python emitter
    python/
```
### Parameter, Option, and Environment variable interpolation

Add two new sections to the yaml configuration that specify command-line parameters and environment variables that can be used in interpolation.

```yaml

"environment-variables": 
  github-root-folder
parameters:
  "python-sdk-folder":
    default: "{env.github-root-folder}/azure-sdk-for-python/sdk/"
"@azure-tools/cadl-python":
  "package-name": compute
  "emitter-output-folder": "{python-sdk-folder}/{package-name}
```

Parameter values are provided on the command line using a new `--arg` parameter:

```bash
cadl compile . --arg python-sdk-folder=./custom
```

When resolving the `emitterOuputDir` passed to emitters, the cli will resolve references to
- Parameters from the 'parameters' section
- Environment variables from the `"environment-variables"` section (note that these must be prefixed with `env.` to differentiate from other settings. (i.e. `{env.github-directory}` refers to an environment variable, while `{github-directory}` refers to a parameter or emitter option for the given emitter.
- Emitter options for the given emitter

Any circular references or references to unknown values will result in an error.

## Relative paths
Paths starting with `.` or `..` will continue to be accepted on the command line, but will not be allowed in the configuration file.
- On the command line `.` refers to the current working directory
- In configuration, `output-dir` and `emitter-output-dir` values must start with `{project-root}` or `{cwd}` or another interpolated value, or absolute paths.

## Azure service example

```yaml
"output-dir": "{env.github-root-folder}"
"environment-variables":
  "github-root-folder"
parameters:
  "python-sdk-folder": 
    default: "{output-dir}/azure-sdk-for-python/"
  "csharp-sdk-folder": 
    default: "{output-dir}/azure-sdk-for-net/"
  "openapi-folder": 
    default: "{project-root}/../resource-manager/"
  "service-directory-name":
    default: compute
  
emitters:
  "@azure-tools/cadl-python":
    "package-name": mypackage 
    "emitter-output-dir": "{python-sdk-folder}/sdk/{service-directory-name}/{package-name}"
  "@azure-tools/cadl-csharp":
    "package-name": "MyPackage"
    "emitter-output-dir": "{csharp-sdk-folder}/sdk/{service-directory-name}/{package-name}"
  "@azure-tools/cadl-autorest":
    "emitter-output-dir": "{openapi-folder}/Microsoft.Compute/"
```

## Appendix: interpolating file paths based on information from the spec
There are cases in which emitters may determine file paths based on information only available from the specification.  This might include:
- api-version
- api-version status (preview ot stable)
- File names based on Cadl types

Currently, we leave it up to the emitter how to construct file paths below the output directory.  If it becomes desirable to make these file paths configurable, we could implement a similar interpolation scheme using a set of either known or emitter-specific interpolated values and a helper.

The known intterpolated values might include:
- `{api-version}`
- `{api-version-status}`
- `{file-name}`

And the helper function might look like this:
```ts
export function resolveScopedPath (
  template: string,
  args: Record<string, string>
): string;
```

usage could be as follows:

```ts
const template `../resource-manager/{service-namespace}/{subservice-name?}/{api-version-status}/{api-version}/{file-name}.json`
//                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ that part already been resolved by the emitter options
resolveScopedPath(template, args: {
  "api-version": "2022-01-01-preview",
  "api-version-status": "preview",
  "service-namespace": "Microsoft.Compute",
  "file-name": context.options["file-name"] ?? "openapi",
}); // ../resource-manager/Microsoft.Compute/preview/2022-01-01/openapi.json
resolveScopedPath(template, args: {
  "api-version": "2022-03-01",
  "api-version-status": "stable",
  "service-namespace": "Microsoft.Compute",
  "service-name": "DiskRP",
  "file-name": context.options["file-name"] ?? "openapi",
}); // ../resource-manager/Microsoft.Compute/DiskRP/preview/2022-01-01/openapi.json
```
