### ISSUE TITLE
`--option` doesn't work if using `--emit` with the path to the emitter

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1213]
If you are using 

```bash
cadl compile  . --emit=/path/to/my-emitter --option "my-emitter.option1=value1"
```
the options are not resovled. 

Think this is a problem because we merge the emitter options with the emitter name before we actually know the emitter name. 

This would be the `emitters` option passed to the cadl compiler.
```ts
emitters: {
   "/path/to/my-emitter": {}
}
```

`my-emitter` options is omitted because `my-emitter` isn't in the `--emit` list.

To resolve we would need to be able to figure out the real name of the emitter from `--emit` or change the compiler options so the compiler can resolve that itself later.

## Option 1: 
Have the cli load the value of `--emit` to resolve the emitter name

No change to the user but might be a bit costly and having the CLI look go out of its scope of work.
## Option 2: 

Change the cadl-project file to match more the cli 1 to 1

```yaml
emit: 
 - @cadl-lang/openapi3
 - /path/to/other-emitter
emitterOptions:
  @cadl-lang/openapi3:
     output-dir: abc
  other-emitter:
    option1: true
```

This is definitely more verbose but would be more explicit it would also allow a user to setup the config for an emitter that they don't want to run by default

**Comment by tjprescott** [comment]
Wasted several hours on account of this bug. The workaround is to specify the path for every option (which is super gross)
![image](https://user-images.githubusercontent.com/5723682/197574426-6b8af589-1626-4481-99cb-3b9415f3ece3.png)

**Comment by timotheeguerin** [comment]
Go with option 2 but reanem `emitterOptions` to `options`

```yaml
emit: 
 - /path/to/other-emitter
options:
  @cadl-lang/openapi3:
    output-dir: abc
  other-emitter:
    option1: true
```
