### ISSUE TITLE
`@body body: bytes` should produce `format: binary` not `format: bytes`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#124]
Current having a response like 
```cadl
model Response {
  @contentType: "application/octet-stream";
  @body body: bytes;
}
```

Should produce
```yaml
content: 
  application/octect-stream:
    schema: 
       type: "string"
       format: "binary"

```

fix in: 
- [x] openapi3 https://github.com/microsoft/cadl/pull/125
- [x] cadl-autorest https://github.com/Azure/cadl-azure/pull/1065
