### ISSUE TITLE
December spring breaking changes and deprecations

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1263]

**Comment by timotheeguerin** [comment]
## [Api] Change to `onEmit` signature

The signature of `onEmit` has been updated.

**Before**

```ts
export function $onEmit(program: Program, options: MyEmitterOptions);
```

**Now**

```ts
export function $onEmit(context: EmitContext);
```

Access properties

| Before                  | Now                                                                                                         |
| ----------------------- | ----------------------------------------------------------------------------------------------------------- |
| `program`               | `context.program`                                                                                           |
| `options`               | `context.options`                                                                                           |
| `options["output-dir"]` | `context.emitterOutputDir` [See details](#cadl-api-emitter-option-output-dir-renamed-to-emitter-output-dir) |

## [Cadl] [Api] Emitter option `output-dir` renamed to `emitter-output-dir`

The option has been renamed for all emitters as `emitter-output-dir` is now managed in the compiler
Before

```yaml
emitters:
  my-emitter:
    output-dir: /path/to-output-dir
```

Now

```yaml
emitters:
  my-emitter:
    emitter-output-dir: {output-dir}/for-this-emitter
#                        ^ can now reference the common output-dir
```

### Change to api

**Before**

```ts
export function $onEmit(program: Program, options: MyEmitterOptions) {
  const outputDir = options["output-dir"];
}
```

**Now**

```ts
export function $onEmit(context: EmitContext) {
  const outputDir = context.emitterOutputDir;
}
```
