### ISSUE TITLE
Update cadl config to more closely match command line

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1281]
Implementation issue for: https://github.com/microsoft/cadl/issues/1213

Update configuration to have separate sections for enabled emitters and emitter options:
```yaml
emit: 
 - /path/to/other-emitter
options:
  @cadl-lang/openapi3:
    output-dir: abc
  other-emitter:
    option1: true
```
