### ISSUE TITLE
Implementation: Unreachable models and visibility logic update

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1355]
From design https://github.com/microsoft/cadl/issues/1125#issuecomment-1310754553

1. try to represent as a single model (with readonly if possible)
2. if not generate each different model but don't include base model
3. unreachable models stays as they are: included unless `omit-unreachable-types: true`
```cadl
model User {
  name: string;
  @visibility("create") password: string;
  @visibility("read") id: string;
}
op create(user: User): void;
op read(): User;
```

```yaml
components:
  schemas:
    UserRead:
      properties:
        id: { type: string }
        name: { type: string }
    UserCreate:
      properties:
        name: { type: string }
        password: { type: string }
    
    # Never include non used visibility
    # UserUpdate:
    #   properties:
    #    ...
       
    # this schema is not referenced in operations 
    User:
      properties:
        id: { type: string }
        name: { type: string }
        password: { type: string }
```
