### ISSUE TITLE
Library options

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1425]
Currently we have a way for emitter to define options but no way for a library to do so.

We kept the design of option configuration open for this purpose but didn't have a real use case.
Dpg teams want to be able to define some shared DPG options.

```yaml
emit:
  - @azure-tools/cadl-python
options: 
  @azure-tools/cadl-dpg
     common-option: "abc"
  @azure-tools/cadl-python:
     python-specfic: "def"
  @azure-tools/cadl-csharp:
     csharp-specfic: "xyz"
```

And then the dpg library can expose those common options via an helper.

**Comment by markcowl** [comment]
```yaml
emit:
  - @azure-tools/cadl-python
options: 
  global-options
     common-option: "abc"
  @azure-tools/cadl-python:
     python-specfic: "def"
  @azure-tools/cadl-csharp:
     csharp-specfic: "xyz"
```

**Comment by markcowl** [comment]
```yaml
emit:
  - @azure-tools/cadl-python
options: 
  @azure-tools/cadl-python:
    common-option: "abc"
     python-specfic: "def"
  @azure-tools/cadl-csharp:
     common-option: "abc"
     csharp-specfic: "xyz"
```
