### ISSUE TITLE
Breaking changes entry January sprint

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1497]

**Comment by timotheeguerin** [comment]
## `@cadl-lang/openapi3` Default output-file is `openapi.yaml`

As the openapi3 emitter added support for serializing the openapi document to yaml it changed the default to emit yaml to `openapi.yaml`.


```yaml
options:
  @cadl-lang/openapi3:
     file-type: json
```

or alternatively specify the name of the file you'd want

```yaml
options:
  @cadl-lang/openapi3:
     output-file: custom.json
```
