### ISSUE TITLE
OpenAPI3 emitter generates $refs incorrectly in yaml output

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#1546]
The OpenAPI3 emitter recently added support for output to yaml, but the $ref's produced in yaml output use incorrect structure -- the ref is formatted as an object with a "value" rather than simply as a string.  E.g.
```
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref:
                  value: '#/components/schemas/Error'
```
should be
```
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```
[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd5RcQMxXhjb2Rly0BtZXNzYWdlymTEOnJvdXRlKCIvd%2BUAr3MiKQpAdGFnKOcBBcQQaW50ZXJm5ADnxxTFXEDkAN1saXN0KCk6xxlbXSB8xn7EbsUh5ADtKOUA3%2BsA3ckxzS9wb3N0IGNyZWF0ZSguLi7GItcrYXRjaCDmAUHfLEBkZWxldGUgxgf0AIt2b2lkzTLnARJ7aWR9L2FuYWx5emUiKecAoMcQ1EjGCcpKfQo%3D)
